const cardImages = [
    require('../public/images/cards/share-0007-2.jpg'),
    require('../public/images/cards/share-0007.jpg'),
    require('../public/images/cards/share-0107-2.jpg'),
    require('../public/images/cards/share-0107-3.jpg'),
    require('../public/images/cards/share-0107-4.jpg'),
    require('../public/images/cards/share-0107-5.jpg'),
    require('../public/images/cards/share-0107-6.jpg'),
    require('../public/images/cards/share-0107.jpg'),
    require('../public/images/cards/share-0207-2.jpg'),
    require('../public/images/cards/share-0207-3.jpg'),
    require('../public/images/cards/share-0207.jpg'),
    require('../public/images/cards/share-0307.jpg'),
    require('../public/images/cards/share-0407-2.jpg'),
    require('../public/images/cards/share-0407-3.jpg'),
    require('../public/images/cards/share-0407.jpg'),
    require('../public/images/cards/share-0507.jpg'),
    require('../public/images/cards/share-0607-2.jpg'),
    require('../public/images/cards/share-0607.jpg'),
    require('../public/images/cards/share-0707-2.jpg'),
    require('../public/images/cards/share-0707-3.jpg'),
    require('../public/images/cards/share-0707-4.jpg'),
    require('../public/images/cards/share-0707.jpg'),
    require('../public/images/cards/share-0807-2.jpg'),
    require('../public/images/cards/share-0807.jpg'),
    require('../public/images/cards/share-0907.jpg'),
    require('../public/images/cards/share-1007-2.jpg'),
    require('../public/images/cards/share-1007.jpg'),
    require('../public/images/cards/share-1107-2.jpg'),
    require('../public/images/cards/share-1107.jpg'),
    require('../public/images/cards/share-1207-2.jpg'),
    require('../public/images/cards/share-1207-3.jpg'),
    require('../public/images/cards/share-1207-4.jpg'),
    require('../public/images/cards/share-1207-5.jpg'),
    require('../public/images/cards/share-1207.jpg'),
    require('../public/images/cards/share-1307-2.jpg'),
    require('../public/images/cards/share-1307.jpg'),
    require('../public/images/cards/share-1407-2.jpg'),
    require('../public/images/cards/share-1407-3.jpg'),
    // require('/images/cards/share-1407-4'),
    // require('/images/cards/share-1407-5'),
    // require('/images/cards/share-1407'),
    // require('/images/cards/share-1507-2'),
    // require('/images/cards/share-1507'),
    // require('/images/cards/share-1607-2'),
    // require('/images/cards/share-1607'),
    // require('/images/cards/share-1707-2'),
    // require('/images/cards/share-1707-3'),
    // require('/images/cards/share-1707'),
    // require('/images/cards/share-1807-2'),
    // require('/images/cards/share-1807-3'),
    // require('/images/cards/share-1807'),
    // require('/images/cards/share-1907-2'),
    // require('/images/cards/share-1907-3'),
    // require('/images/cards/share-1907'),
    // require('/images/cards/share-2007-2'),
    // require('/images/cards/share-2007-3'),
    // require('/images/cards/share-2007'),
    // require('/images/cards/share-2107-2'),
    // require('/images/cards/share-2107-3'),
    // require('/images/cards/share-2107'),
    // require('/images/cards/share-2207-2'),
    // require('/images/cards/share-2207-3'),
    // require('/images/cards/share-2207'),
    // require('/images/cards/share-2307-2'),
    // require('/images/cards/share-2307'),
    // require('/images/cards/share-2407-2'),
    // require('/images/cards/share-2407-3'),
    // require('/images/cards/share-2407-4'),
    // require('/images/cards/share-2407-5'),
    // require('/images/cards/share-2407-6'),
    // require('/images/cards/share-2407'),
    // require('/images/cards/share-2507-2'),
    // require('/images/cards/share-2507-3'),
    // require('/images/cards/share-2507-4'),
    // require('/images/cards/share-2507'),
    // require('/images/cards/share-2607-2'),
    // require('/images/cards/share-2607'),
    // require('/images/cards/share-2807-2'),
    // require('/images/cards/share-2807-3'),
    // require('/images/cards/share-2807'),
    // require('/images/cards/share-2907-2'),
    // require('/images/cards/share-2907-3'),
    // require('/images/cards/share-2907-4'),
    // require('/images/cards/share-2907'),
    // require('/images/cards/share-3007-2'),
    // require('/images/cards/share-3007-3'),
    // require('/images/cards/share-3007-4'),
    // require('/images/cards/share-3007-5'),
    // require('/images/cards/share-3007-6'),
    // require('/images/cards/share-3007'),
    // require('/images/cards/share-3107-2'),
    // require('/images/cards/share-3107'),
    // require('/images/cards/share-3307-2'),
    // require('/images/cards/share-3307'),
    // require('/images/cards/share-3407-2'),
    // require('/images/cards/share-3407-3'),
    // require('/images/cards/share-3407-4'),
    // require('/images/cards/share-3407'),
    // require('/images/cards/share-3507-2'),
    // require('/images/cards/share-3507'),
    // require('/images/cards/share-3607-2'),
    // require('/images/cards/share-3607-3'),
    // require('/images/cards/share-3607'),
    // require('/images/cards/share-3707-2'),
    // require('/images/cards/share-3707-3'),
    // require('/images/cards/share-3707-4'),
    // require('/images/cards/share-3707'),
    // require('/images/cards/share-3807-2'),
    // require('/images/cards/share-3807-3'),
    // require('/images/cards/share-3807-4'),
    // require('/images/cards/share-3807-5'),
    // require('/images/cards/share-3807'),
    // require('/images/cards/share-3907-2'),
    // require('/images/cards/share-3907-3'),
    // require('/images/cards/share-3907'),
    // require('/images/cards/share-4007-2'),
    // require('/images/cards/share-4007-3'),
    // require('/images/cards/share-4007'),
    // require('/images/cards/share-4107'),
    // require('/images/cards/share-4207-2'),
    // require('/images/cards/share-4207-3'),
    // require('/images/cards/share-4207'),
    // require('/images/cards/share-4307-2'),
    // require('/images/cards/share-4307-3'),
    // require('/images/cards/share-4307'),
    // require('/images/cards/share-4407-2'),
    // require('/images/cards/share-4407-3'),
    // require('/images/cards/share-4407'),
    // require('/images/cards/share-4507-2'),
    // require('/images/cards/share-4507-3'),
    // require('/images/cards/share-4507-4'),
    // require('/images/cards/share-4507-5'),
    // require('/images/cards/share-4507-6'),
    // require('/images/cards/share-4507'),
    // require('/images/cards/share-4607-2'),
    // require('/images/cards/share-4607-3'),
    // require('/images/cards/share-4607-4'),
    // require('/images/cards/share-4607'),
    // require('/images/cards/share-4707'),
    // require('/images/cards/share-4807'),
    // require('/images/cards/share-5007-2'),
    // require('/images/cards/share-5007-3'),
    // require('/images/cards/share-5007'),
    // require('/images/cards/share-5107-2'),
    // require('/images/cards/share-5107-3'),
    // require('/images/cards/share-5107-4'),
    // require('/images/cards/share-5107-5'),
    // require('/images/cards/share-5107-6'),
    // require('/images/cards/share-5107'),
    // require('/images/cards/share-5207'),
    // require('/images/cards/share-5307-2'),
    // require('/images/cards/share-5307-3'),
    // require('/images/cards/share-5307-4'),
    // require('/images/cards/share-5307-5'),
    // require('/images/cards/share-5307'),
    // require('/images/cards/share-5407'),
    // require('/images/cards/share-5507-2'),
    // require('/images/cards/share-5507'),
    // require('/images/cards/share-5607-2'),
    // require('/images/cards/share-5607-3'),
    // require('/images/cards/share-5607-4'),
    // require('/images/cards/share-5607-5'),
    // require('/images/cards/share-5607'),
    // require('/images/cards/share-5707-2'),
    // require('/images/cards/share-5707-3'),
    // require('/images/cards/share-5707'),
    // require('/images/cards/share-5807'),
    // require('/images/cards/share-5907-2'),
    // require('/images/cards/share-5907')
];
  
export default cardImages;


